// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABxTGSV8P1nyRNq9sg3Lyh_h0NeA6Rde4',
    appId: '1:150173443895:web:ed4016a1eff6c3aa2c9cb2',
    messagingSenderId: '150173443895',
    projectId: 'ongojisin-testpj',
    authDomain: 'ongojisin-testpj.firebaseapp.com',
    storageBucket: 'ongojisin-testpj.firebasestorage.app',
    measurementId: 'G-KK6S5DKT8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0cjpx8RkMD8VXWSjxaV8CU5F5jd-tjDM',
    appId: '1:150173443895:android:cf32c82321321c942c9cb2',
    messagingSenderId: '150173443895',
    projectId: 'ongojisin-testpj',
    storageBucket: 'ongojisin-testpj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ShTTLe20ai0TVhMZh3hpI_6GBe49LdQ',
    appId: '1:150173443895:ios:be5433b4dd97f62a2c9cb2',
    messagingSenderId: '150173443895',
    projectId: 'ongojisin-testpj',
    storageBucket: 'ongojisin-testpj.firebasestorage.app',
    iosBundleId: 'com.example.ongojishin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABxTGSV8P1nyRNq9sg3Lyh_h0NeA6Rde4',
    appId: '1:150173443895:web:e26fe13e4c01f2222c9cb2',
    messagingSenderId: '150173443895',
    projectId: 'ongojisin-testpj',
    authDomain: 'ongojisin-testpj.firebaseapp.com',
    storageBucket: 'ongojisin-testpj.firebasestorage.app',
    measurementId: 'G-SN5H5ZBN2X',
  );
}
