import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
// import 'firebase_options.dart'; // To be generated by flutterfire configure
import 'theme/app_theme.dart';
import 'screens/home_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  try {
    // For local run without configuration, we can skip options or use a try-catch
    await Firebase.initializeApp(
      // options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    print("Firebase initialization failed (expected if not configured): $e");
  }

  runApp(const OngoJiShinApp());
}

class OngoJiShinApp extends StatelessWidget {
  const OngoJiShinApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '온고지신',
      theme: AppTheme.theme, // Use the custom theme
      home: const HomeScreen(), // Set Home Screen
      debugShowCheckedModeBanner: false,
    );
  }
}

// Temporary placeholder for DefaultFirebaseOptions if the file doesn't exist yet
// logic to handle missing file requires specific build-time check or user action.
// For compilation safety in this environment without the real file:
class DefaultFirebaseOptions {
  static var currentPlatform; 
}
